TokenInfo(type=57 (ENCODING), string='utf-8', start=(0, 0), end=(0, 0), line='')
TokenInfo(type=56 (NL), string='\n', start=(1, 0), end=(1, 1), line='\n')
TokenInfo(type=1 (NAME), string='import', start=(2, 0), end=(2, 6), line='import six\n')
TokenInfo(type=1 (NAME), string='six', start=(2, 7), end=(2, 10), line='import six\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(2, 10), end=(2, 11), line='import six\n')
TokenInfo(type=1 (NAME), string='from', start=(3, 0), end=(3, 4), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=1 (NAME), string='six', start=(3, 5), end=(3, 8), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=53 (OP), string='.', start=(3, 8), end=(3, 9), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=1 (NAME), string='moves', start=(3, 9), end=(3, 14), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=53 (OP), string='.', start=(3, 14), end=(3, 15), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=1 (NAME), string='urllib', start=(3, 15), end=(3, 21), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=1 (NAME), string='import', start=(3, 22), end=(3, 28), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=1 (NAME), string='parse', start=(3, 29), end=(3, 34), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=1 (NAME), string='as', start=(3, 35), end=(3, 37), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=1 (NAME), string='urlparse', start=(3, 38), end=(3, 46), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(3, 46), end=(3, 47), line='from six.moves.urllib import parse as urlparse\n')
TokenInfo(type=56 (NL), string='\n', start=(4, 0), end=(4, 1), line='\n')
TokenInfo(type=1 (NAME), string='test', start=(5, 0), end=(5, 4), line='test = six.text_type("truc")\n')
TokenInfo(type=53 (OP), string='=', start=(5, 5), end=(5, 6), line='test = six.text_type("truc")\n')
TokenInfo(type=1 (NAME), string='six', start=(5, 7), end=(5, 10), line='test = six.text_type("truc")\n')
TokenInfo(type=53 (OP), string='.', start=(5, 10), end=(5, 11), line='test = six.text_type("truc")\n')
TokenInfo(type=1 (NAME), string='text_type', start=(5, 11), end=(5, 20), line='test = six.text_type("truc")\n')
TokenInfo(type=53 (OP), string='(', start=(5, 20), end=(5, 21), line='test = six.text_type("truc")\n')
TokenInfo(type=3 (STRING), string='"truc"', start=(5, 21), end=(5, 27), line='test = six.text_type("truc")\n')
TokenInfo(type=53 (OP), string=')', start=(5, 27), end=(5, 28), line='test = six.text_type("truc")\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(5, 28), end=(5, 29), line='test = six.text_type("truc")\n')
TokenInfo(type=1 (NAME), string='url', start=(6, 0), end=(6, 3), line='url = urlparse.urlparse(\n')
TokenInfo(type=53 (OP), string='=', start=(6, 4), end=(6, 5), line='url = urlparse.urlparse(\n')
TokenInfo(type=1 (NAME), string='urlparse', start=(6, 6), end=(6, 14), line='url = urlparse.urlparse(\n')
TokenInfo(type=53 (OP), string='.', start=(6, 14), end=(6, 15), line='url = urlparse.urlparse(\n')
TokenInfo(type=1 (NAME), string='urlparse', start=(6, 15), end=(6, 23), line='url = urlparse.urlparse(\n')
TokenInfo(type=53 (OP), string='(', start=(6, 23), end=(6, 24), line='url = urlparse.urlparse(\n')
TokenInfo(type=56 (NL), string='\n', start=(6, 24), end=(6, 25), line='url = urlparse.urlparse(\n')
TokenInfo(type=3 (STRING), string='"http://www.cwi.nl:80/%7Eguido/Python.html"', start=(7, 4), end=(7, 47), line='    "http://www.cwi.nl:80/%7Eguido/Python.html"\n')
TokenInfo(type=56 (NL), string='\n', start=(7, 47), end=(7, 48), line='    "http://www.cwi.nl:80/%7Eguido/Python.html"\n')
TokenInfo(type=53 (OP), string=')', start=(8, 0), end=(8, 1), line=')\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(8, 1), end=(8, 2), line=')\n')
TokenInfo(type=56 (NL), string='\n', start=(9, 0), end=(9, 1), line='\n')
TokenInfo(type=1 (NAME), string='boom', start=(10, 0), end=(10, 4), line='boom = [\n')
TokenInfo(type=53 (OP), string='=', start=(10, 5), end=(10, 6), line='boom = [\n')
TokenInfo(type=53 (OP), string='[', start=(10, 7), end=(10, 8), line='boom = [\n')
TokenInfo(type=56 (NL), string='\n', start=(10, 8), end=(10, 9), line='boom = [\n')
TokenInfo(type=1 (NAME), string='six', start=(11, 4), end=(11, 7), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string='.', start=(11, 7), end=(11, 8), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=1 (NAME), string='text_type', start=(11, 8), end=(11, 17), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string='(', start=(11, 17), end=(11, 18), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=3 (STRING), string='"a"', start=(11, 18), end=(11, 21), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string=')', start=(11, 21), end=(11, 22), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string=',', start=(11, 22), end=(11, 23), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=1 (NAME), string='six', start=(11, 24), end=(11, 27), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string='.', start=(11, 27), end=(11, 28), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=1 (NAME), string='text_type', start=(11, 28), end=(11, 37), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string='(', start=(11, 37), end=(11, 38), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=3 (STRING), string='"b"', start=(11, 38), end=(11, 41), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string=')', start=(11, 41), end=(11, 42), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string=',', start=(11, 42), end=(11, 43), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=1 (NAME), string='six', start=(11, 44), end=(11, 47), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
TokenInfo(type=53 (OP), string='.', start=(11, 47), end=(11, 48), line='    six.text_type("a"), six.text_type("b"), six.text_type("c")\n')
