from sys import exit

from pbr.version import VersionInfo

from sixectomy import cli
from sixectomy.exceptions import SixectomyException
from sixectomy.models import Analyze
from sixectomy.reports import Report


def main():
    args = cli.argparser().parse_args()
    version = VersionInfo("sixectomy")
    if args.version:
        print("sixectomy v{version}".format(version=version))
        return 0
    filename = args.file
    if not filename:
        return 0

    try:
        analyze = Analyze(filename)
    except SixectomyException as err:
        print(str(err))
        return 1
    else:
        report = Report()
        report.rendering("cli.txt", analyze)
    footer = "Generated by sixectomy v{version}".format(version=version)
    print("-" * len(footer))
    print(footer)
    print("-" * len(footer))
    return 0


if __name__ == "__main__":
    exit(main())
